enable_cache: False
extra:
  tags: zenfile
settings:
  docker:
    required_integrations:
      - facets
      - lightgbm
      - xgboost
      - seldon
    requirements:
      - statsmodels
      - optuna
      - statsmodels
      - feature_engine